### ISSUE TITLE
where is mongodb being used ?

### ISSUE THREAD

**Issue by mHz28** [jussikinnula/angular-socket-io-chat#6]

**Comment by navneetsharma1988** [comment]
Hi,

I want to make this application for Customer care so can you please tell me how can customer care select a user before sending the message? I can see in message scheme there is 'to' property but never being used

**Comment by jussikinnula** [comment]
MongoDB is currently used to store earlier channel messages. Adding support for private messages would require at least user registration (e.g. separate database with user nicknames), and then add support for chatrooms without name - but with two or more users (e.g. private message channels).
